# Generated by Django 5.2.7 on 2025-10-31 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('objetivo', models.TextField(blank=True, verbose_name='Objetivo/Pauta')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('local', models.CharField(blank=True, max_length=120)),
                ('link', models.URLField(blank=True, verbose_name='Link da reunião')),
                ('participantes', models.CharField(help_text='Separe os nomes por vírgula', max_length=255)),
                ('anexos', models.FileField(blank=True, null=True, upload_to='anexos_reunioes/')),
                ('status', models.CharField(choices=[('Agendada', 'Agendada'), ('Realizada', 'Realizada'), ('Cancelada', 'Cancelada')], default='Agendada', max_length=40)),
                ('observacoes', models.TextField(blank=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ultimo_editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reunioes_editadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reunioes_criadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
