# Generated by Django 5.2.7 on 2025-11-01 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_dados', '0004_tarefa_data_fim_tarefa_data_inicio'),
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_auditoria', models.CharField(choices=[('Interna', 'Interna'), ('Externa', 'Externa'), ('Cliente', 'Cliente'), ('Fornecedor', 'Fornecedor')], max_length=30)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('unidade', models.CharField(max_length=100)),
                ('responsavel', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Agendada', 'Agendada'), ('Concluída', 'Concluída'), ('Cancelada', 'Cancelada'), ('Pendente', 'Pendente')], max_length=20)),
                ('comentarios', models.TextField(blank=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='banco_dados.projeto')),
                ('ultimo_editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
