# Generated by Django 5.2.7 on 2025-11-01 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_dados', '0005_alter_projeto_usuario'),
        ('dashboard', '0002_agendaauditoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaauditoria',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='banco_dados.projeto'),
        ),
    ]
