# Generated by Django 5.2.7 on 2025-11-03 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_add_planta_recorrencia_reuniao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reuniao',
            name='link',
        ),
    ]
