# Generated by Django 5.2.7 on 2025-11-05 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_reuniao_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='reuniao',
            name='pausada',
            field=models.BooleanField(default=False),
        ),
    ]
