# Generated by Django 5.2.7 on 2025-10-29 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_dados', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome do projeto')),
                ('responsavel', models.CharField(max_length=100, verbose_name='Responsável')),
                ('area_responsavel', models.CharField(choices=[('Supervisão', 'Supervisão'), ('Qualidade', 'Qualidade'), ('Operação', 'Operação'), ('RH', 'RH'), ('Manutenção', 'Manutenção'), ('HSE', 'HSE')], max_length=20, verbose_name='Área responsável')),
                ('data_inicio', models.DateField(verbose_name='Data início')),
                ('data_fim', models.DateField(verbose_name='Data fim')),
                ('unidade', models.CharField(choices=[('Santo André', 'Santo André'), ('Gravataí', 'Gravataí'), ('Todas', 'Todas')], max_length=20, verbose_name='Unidade')),
                ('status', models.PositiveIntegerField(default=0, verbose_name='% concluído')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data criação')),
                ('usuario', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome da tarefa')),
                ('concluida', models.BooleanField(default=False, verbose_name='Concluída')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='banco_dados.projeto')),
            ],
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
        migrations.AddField(
            model_name='projeto',
            name='tarefas_associadas',
            field=models.ManyToManyField(blank=True, related_name='projetos_associados', to='banco_dados.tarefa', verbose_name='Tarefas associadas'),
        ),
    ]
