# Generated by Django 5.2.7 on 2025-10-30 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_dados', '0002_projeto_tarefa_delete_pessoa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='responsavel',
            field=models.CharField(default='', max_length=100, verbose_name='Responsável'),
        ),
    ]
