# Generated by Django 5.2.7 on 2025-10-30 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_dados', '0003_tarefa_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data fim'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data início'),
        ),
    ]
