# Generated by Django 5.2.7 on 2025-11-04 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_dados', '0005_alter_projeto_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='status',
            field=models.PositiveIntegerField(default=0, verbose_name='Status (%)'),
        ),
    ]
