# Generated by Django 5.2.7 on 2025-11-05 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_dados', '0007_alter_tarefa_status_to_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
    ]
