# Generated by Django 5.2.7 on 2025-11-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_dados', '0008_projeto_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
    ]
